### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by thisconnect** [syntax-tree/hast-util-to-mdast#54]
### Subject of the issue

This markup errors:
https://github.com/syntax-tree/hast-util-to-mdast/pull/53/files#diff-b6b8d72f26f12669066c4e2850f557c7

for some odd reason, in my test, it only errored if there are 2 input[type=hidden] (inside the table)

 `TypeError: Cannot read property 'length' of undefined`

### Your environment

*   **OS**: macos
*   **Packages**: hast-util-to-mdast@5.0.0
*   **Env**: Node v12.5.0, NPM 6.10.1

### Steps to reproduce

PR: https://github.com/syntax-tree/hast-util-to-mdast/pull/53
Error on travis: https://travis-ci.org/syntax-tree/hast-util-to-mdast/jobs/567626032#L699

### Expected behaviour

What should happen?

no error

### Actual behaviour

What happens instead?

```
 TypeError: Cannot read property 'length' of undefined
    at one (./node_modules/hast-util-to-mdast/lib/handlers/table.js:77:24)
    at patch (./node_modules/hast-util-to-mdast/lib/handlers/table.js:68:5)
    at table (./node_modules/hast-util-to-mdast/lib/handlers/table.js:10:43)
    at one (./node_modules/hast-util-to-mdast/lib/one.js:24:51)
    at all (./node_modules/hast-util-to-mdast/lib/all.js:15:14)
    at wrapped (./node_modules/hast-util-to-mdast/lib/util/wrap-children.js:9:15)
    at one (./node_modules/hast-util-to-mdast/lib/one.js:24:51)
    at all (./node_modules/hast-util-to-mdast/lib/all.js:15:14)
    at cell (./node_modules/hast-util-to-mdast/lib/handlers/table-cell.js:8:31)
    at one (./node_modules/hast-util-to-mdast/lib/one.js:24:51)
```

**Comment by thisconnect** [comment]
oups I must have hit some GH shortcut and submitted this issue a bit too early... will update
